apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vegaproject.io-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - vegaproject.io
  resources:
  - calculations
  - calculationbulks
  - calculationbulkfactories
  - workerpools
  verbs:
  - get
  - list
  - watch
  - create
  - delete
